# Site settings
title: "András's resume"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "András Maróy"
resume_title:                   "Engineering Manager"

# used for the contact button in _layouts/resume.html
#resume_contact_email:           "lisasimpson@youremailaddress.com"

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone:       "555-7334"
resume_contact_address:         "Sandgata 2, 7012 Trondheim, Norway"

#resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>A developer with experiences within machine learning and backend development. As a developer I really like the challenge machine learning gives and the ability to be creative. The last year I also completed a course in Parallel Programming covering CUDA, OpenMPI and basic pthread & openmp use.  </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        ""

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/andrasmaroy"
  # resume_twitter_url:           ""
  # resume_dribbble_url:          ""
  # resume_facebook_url:          ""
  resume_linkedin_url:          "https://www.linkedin.com/in/andrasmaroy"
  # resume_instagram_url:         ""
  # resume_website_url:           ""
  resume_pdf_url:               "https://github.com/andrasmaroy/resume/raw/gh-pages/webpage/resume.pdf"
  # resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
