# Site settings
title: "András's resume"
description: "A static page hosting András Maróy's resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "András Maróy"
resume_title:                   "Engineering Manager"

# used for the contact button in _layouts/resume.html
resume_contact_email:           ""

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: |-
  <p>Engineering manager with a background in software engineering and devops in both product focused and outsource companies. Interested in psychology and teaching.</p>
  <div>
    <ul>
      <li><b>Champions teamwork.</b> Removes obstacles in front of the team to enable them to work on what matters.</li>
      <li><b>Fosters professional growth.</b> Focuses on finding the right growth area for team members and helps them achieve their goals.</li>
      <li><b>Gets the right things done.</b> Makes sure that the right feature gets implemented not to waste development time.</li>
    </ul>
  </div>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        ""

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_sidehustle:      true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/andrasmaroy"
  # resume_twitter_url:           ""
  # resume_dribbble_url:          ""
  # resume_facebook_url:          ""
  resume_linkedin_url:          "https://www.linkedin.com/in/andrasmaroy"
  # resume_instagram_url:         ""
  # resume_website_url:           ""
  # resume_pdf_url:               "https://github.com/andrasmaroy/resume/raw/gh-pages/webpage/resume.pdf"
  # resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
